default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cryptocurrency_exchanger_development

test:
  <<: *default
  database: cryptocurrency_exchanger_test

production:
  <<: *default
  database: cryptocurrency_exchanger_production
  username: cryptocurrency_exchanger
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
