default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cryptocurrency_exchanger_development

test:
  <<: *default
  database: cryptocurrency_exchanger_test

production:
  <<: *default
  database: cryptocurrency_exchanger_production
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
